### ISSUE TITLE
getAttribute issue in Chess Practive project

### ISSUE THREAD

**Issue by Ranger-Jay** [Ranger-Jay/PERSONAL-PROJECT-PURE-JS-CHESS-GAME#1]
UInable to resolve why getAttribute issue is occurring as well as the dragDrop element.

Cannot read properties of undefined (reading 'getAttribute')
    at checkIfValid (app.js:94:36)
    at HTMLDivElement.dragDrop (app.js:67:19)

**Comment by Ranger-Jay** [comment]
Issue is now resolved.  the `targetId` property was written in as a previously discarded variable name... `takenId` ... by mistake. Replaced `takenId` with `targetId`, and now all is cool in the world.
